# Docker setup is based on
# https://github.com/rocker-org/rocker/blob/56cb59cc262e9d2c02f9e11cfacab65f0b659c5f/.travis.yml#L17
sudo: required
dist: trusty
language: python
python:
    - "2.7"
services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty

before_install:
     # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

# command to install dependencies
install:
    - pip install tox-travis
    - pip install codecov

#run tests
script:
    - docker version
    - docker info
    - tox

after_success:
    - codecov
